export const interestOptions = [
  'Madlavning',
  'Rejser',
  'Musik',
  'Film',
  'Litteratur',
  'Sport',
  'Løb',
  'Cykling',
  'Tennis',
  'Padel',
  'Vandreture',
  'Fotografi',
  'Kunst',
  'Håndarbejde',
  'Gaming',
  'Yoga',
  'Meditation',
  'Dans',
  'Fitness',
  'Havearbejde',
  'Kæledyr',
  'Brætspil',
  'Fester',
  'Politik',
  'Teknologi',
  'Biler',
  'Mode',
  'Frivilligt arbejde',
  'Mad & vin',
  'Strand',
  'Sejlads',
  'Fiskeri',
  'Skiløb',
  'Snowboard',
  'Camping',
  'Indretning',
  'Podcast',
  'Sprog',
  'Historie',
  'Science fiction',
  'Astrologi',
  'Comedy',
  'Klassisk musik',
  'Elektronisk musik',
  'Jazz',
  'Rock',
  'Kor',
  'Læseklub',
  'Tegneserier',
  'Anime',
  'Manga',
  'DIY-projekter',
  'Opera',
  'Hip-hop',
  'Triatlon',
  'Bage',
  'Vin',
  '\u00d8lbrygning'
];

export const interestCategories = {
  'Madlavning': 'Mad & Gastronomi',
  'Mad & vin': 'Mad & Gastronomi',
  'Rejser': 'Rejser & Udeliv',
  'Strand': 'Rejser & Udeliv',
  'Sejlads': 'Rejser & Udeliv',
  'Camping': 'Rejser & Udeliv',
  'Fiskeri': 'Rejser & Udeliv',
  'Skiløb': 'Rejser & Udeliv',
  'Snowboard': 'Rejser & Udeliv',
  'Vandreture': 'Rejser & Udeliv',
  'Sport': 'Sport & Fitness',
  'Løb': 'Sport & Fitness',
  'Cykling': 'Sport & Fitness',
  'Tennis': 'Sport & Fitness',
  'Padel': 'Sport & Fitness',
  'Fitness': 'Sport & Fitness',
  'Yoga': 'Sport & Fitness',
  'Dans': 'Sport & Fitness',
  'Meditation': 'Velvære',
  'Kunst': 'Kunst & Kultur',
  'Fotografi': 'Kunst & Kultur',
  'Litteratur': 'Kunst & Kultur',
  'Film': 'Kunst & Kultur',
  'Tegneserier': 'Kunst & Kultur',
  'Anime': 'Kunst & Kultur',
  'Manga': 'Kunst & Kultur',
  'Science fiction': 'Kunst & Kultur',
  'Musik': 'Musik',
  'Klassisk musik': 'Musik',
  'Elektronisk musik': 'Musik',
  'Jazz': 'Musik',
  'Rock': 'Musik',
  'Kor': 'Musik',
  'Gaming': 'Underholdning',
  'Brætspil': 'Underholdning',
  'Comedy': 'Underholdning',
  'Podcast': 'Underholdning',
  'Håndarbejde': 'Hobby & Hjem',
  'Havearbejde': 'Hobby & Hjem',
  'Kæledyr': 'Hobby & Hjem',
  'DIY-projekter': 'Hobby & Hjem',
  'Indretning': 'Hobby & Hjem',
  'Teknologi': 'Teknologi',
  'Biler': 'Teknologi',
  'Mode': 'Mode & Stil',
  'Frivilligt arbejde': 'Samfund',
  'Politik': 'Samfund',
  'Sprog': 'Uddannelse',
  'Historie': 'Uddannelse',
  'Astrologi': 'Uddannelse',
  'Fester': 'Socialt',
  'Opera': 'Musik',
  'Hip-hop': 'Musik',
  'Triatlon': 'Sport & Fitness',
  'Bage': 'Mad & Gastronomi',
  'Vin': 'Mad & Gastronomi',
  '\u00d8lbrygning': 'Mad & Gastronomi'
};

export const getInterestCategory = i => interestCategories[i] || 'Andet';
